# Generated by Django 6.0.3 on 2026-03-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='between_streets',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entre calles'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(default=30, max_length=20, verbose_name='Número / Depto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=30, max_length=10, verbose_name='Código postal'),
            preserve_default=False,
        ),
    ]
